name: Build & publish deb package
on:
  workflow_dispatch:
    inputs:
      appversion:
        description: "Tag/Version"
        default: 'v1.0.0'
        required: true

jobs:
    Create_Packages:
        name: Default Job
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4

          - name: Create deb the package
            id: nfpm-deb
            uses: ./.github/actions/nFPM/
            with:
              packager: deb
              config: ./nfpm.yaml

          - name: Get the package name from the output
            run: echo ${{ steps.nfpm-deb.outputs.package }}
            shell: bash

     
          - name: Create the GitHub Release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN }}
            with:
              tag_name: ${{ github.event.inputs.appversion }}
              release_name: ${{ github.event.inputs.appversion }}
              draft: false
              prerelease: false
              
          - name: Upload deb package to Release Asset 
            id: upload-release-asset 
            uses: actions/upload-release-asset@v1
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN }}
            with:
              # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
              # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
              upload_url: ${{ steps.create_release.outputs.upload_url }} 
              asset_path: ${{ steps.nfpm-deb.outputs.package }}
              asset_name: ${{ steps.nfpm-deb.outputs.package }}
              # https://mimetype.io/application/vnd.debian.binary-package
              asset_content_type: application/vnd.debian.binary-package

